config/routes.rb
Gemini::Application.routes.draw do

  resources :interested_users, :only => [:create]

  match '/investor' => 'pages#investor'
  match '/investor/demo' => 'pages#demo'
  match '/investor/deck' => 'pages#deck'
  match '/investor/summary' => 'pages#summary'

  root :to => 'pages#home'

end

app/models/interested_user.rb
class InterestedUser < ActiveRecord::Base
  attr_accessible :email, :name, :state_licensed

  before_save { |user| user.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, :presence=> true, :format=> { :with=> VALID_EMAIL_REGEX },
                    :uniqueness=> true

end

app/controllers/interested_users_controller.rb
class InterestedUsersController < ApplicationController
  # GET /interested_users
  # GET /interested_users.json
  def index
    @interested_users = InterestedUser.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @interested_users }
    end
  end

  # GET /interested_users/1
  # GET /interested_users/1.json
  def show
    @interested_user = InterestedUser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @interested_user }
    end
  end

  # GET /interested_users/new
  # GET /interested_users/new.json
  def new
    @interested_user = InterestedUser.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @interested_user }
    end
  end

  # GET /interested_users/1/edit
  def edit
    @interested_user = InterestedUser.find(params[:id])
  end

  # POST /interested_users
  # POST /interested_users.json
  def create
     @interested_user = InterestedUser.new(params[:interested_user])

     #@interested_user['referer'] = request.referer

    respond_to do |format|
      if @interested_user.save

        UserMailer.signup_email(@interested_user).deliver
        UserMailer.signup_user_email(@interested_user).deliver

        format.html { redirect_to root_path}
        flash[:success] = "Thank you for signing up!"

      else
        format.html { redirect_to root_path}
        flash[:error] = "Please enter a valid email address."
      end
    end
  end

  # PUT /interested_users/1
  # PUT /interested_users/1.json
  def update
    @interested_user = InterestedUser.find(params[:id])

    respond_to do |format|
      if @interested_user.update_attributes(params[:interested_user])
        format.html { redirect_to @interested_user, :notice => 'Interested user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @interested_user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /interested_users/1
  # DELETE /interested_users/1.json
  def destroy
    @interested_user = InterestedUser.find(params[:id])
    @interested_user.destroy

    respond_to do |format|
      format.html { redirect_to interested_users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/interested_users_helper.rb
module InterestedUsersHelper
end

app/views/interested_users/_form.html.erb
<%= form_for(@interested_user) do |f| %>
  <% if @interested_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interested_user.errors.count, "error") %> prohibited this interested_user from being saved:</h2>

      <ul>
      <% @interested_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/interested_users/edit.html.erb
<h1>Editing interested_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @interested_user %> |
<%= link_to 'Back', interested_users_path %>

app/views/interested_users/index.html.erb
<h1>Listing interested_users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @interested_users.each do |interested_user| %>
  <tr>
    <td><%= interested_user.name %></td>
    <td><%= interested_user.email %></td>
    <td><%= link_to 'Show', interested_user %></td>
    <td><%= link_to 'Edit', edit_interested_user_path(interested_user) %></td>
    <td><%= link_to 'Destroy', interested_user, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Interested user', new_interested_user_path %>

app/views/interested_users/new.html.erb
<h1>New interested_user</h1>

<%= render 'form' %>

<%= link_to 'Back', interested_users_path %>

app/views/interested_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @interested_user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @interested_user.email %>
</p>


<%= link_to 'Edit', edit_interested_user_path(@interested_user) %> |
<%= link_to 'Back', interested_users_path %>