config/routes.rb
Gemini::Application.routes.draw do

  resources :interested_users, :only => [:create]

  match '/investor' => 'pages#investor'
  match '/investor/demo' => 'pages#demo'
  match '/investor/deck' => 'pages#deck'
  match '/investor/summary' => 'pages#summary'

  root :to => 'pages#home'

end

app/views/pages/about.html.erb
<% provide(:title, 'About Us')%>
<h1>About</h1>

<h3>Purpose</h3>
<br/>
Vizibid is a Seattle based startup dedicated to finding the best ways to help lawyers find, share, rate, and comment on model forms for legal documents. Our goal is to make relevant, high quality, and reasonably priced model forms widely available to practicing lawyers.
<br/><br/>
<h3>Current Projects</h3>
<br/>
We are currently seeking feedback from lawyers to discover how to improve their experience finding model forms for legal documents. We will use what we learn to build the initial Vizibid service. Because we are going to build what you want, your early feedback on our ideas is extremely important to us.
<br/><br/>

<%= link_to "Complete our Survey", survey_path, :id => "surveylink" %>

app/views/pages/betahome.html.erb
<% provide(:title, 'Home')%>

app/views/pages/demo.html.erb
<% provide(:title, 'Demos')%>
<br/>
<div class = "offset4">
	<h2 >Vizibid prototype demos</h2>
</div>
<hr/>
<div class = "row">
	<div class ="span5">
		<h4>Scenario 1</h4><br/>
		<p>The user wants to find an LLC operating agreement for Washington State. He searches the site and gets results. He then makes his search more specific and looks at the details page for the document. He likes what he sees so he downloads the document</p>
	</div>
	
	<div class = "offset5">
		<%= video_tag(["https://s3.amazonaws.com/gemini-production-files/media1.mp4","https://s3.amazonaws.com/gemini-production-files/media1.ogg"], :controls => true, :size => "565x420", :autobuffer => true, :muted => "true") %>
	</div>
</div>
<hr/>
<div class = "row">
	<div class ="span5">
		<h4>Scenario 2</h4><br/>
		<p>Here the user found the document useful. He signs-in to Vizibid and then up-votes an existing comment, adds a comment, and gives the form a rating.</p>
	</div>

	<div class = "offset5">
		<%= video_tag(["https://s3.amazonaws.com/gemini-production-files/media2.mp4","https://s3.amazonaws.com/gemini-production-files/media2.ogg"], :controls => true, :size => "565x420", :autobuffer => true, :muted => "true") %>
	</div>
</div>
<hr/>
<div class = "row">
	<div class ="span5">
		<h4>Scenario 3</h4><br/>
		<p>Here the user searches for a document. He doesn’t find what he’s looking for so he puts in a request for the document.</p>
	</div>

	<div class = "offset5">
		<%= video_tag(["https://s3.amazonaws.com/gemini-production-files/media3.mp4","https://s3.amazonaws.com/gemini-production-files/media3.ogg"], :controls => true, :size => "565x420", :autobuffer => true, :muted => "true") %>
	</div>
</div>
<hr/>
<div class = "row">
	<div class ="span5">
		<h4>Scenario 4</h4><br/>
		<p>Eventually the user receives email indicating that his request got a response. He checks the response and marks his request as completed since he got what he needed.</p>
	</div>

	<div class = "offset5">
		<%= video_tag(["https://s3.amazonaws.com/gemini-production-files/media4.mp4","https://s3.amazonaws.com/gemini-production-files/media4.ogg"], :controls => true, :size => "565x420", :autobuffer => true, :muted => "true") %>
	</div>
</div>
<br/>

app/views/pages/faq.html.erb
<% provide(:title, 'FAQ')%>

<h1>Frequently Asked Questions</h1>

<h4>What is Vizibid?</h4>
Vizibid is a website to help lawyers find, share, rate, and comment on model forms for legal documents.<br/>

<br/><h4>When will the Vizibid service be available?</h4>
We will make the Vizibid service available as soon as we can. We are currently in the process of gathering enough information from lawyers to learn what lawyers want us to build. Once we have enough information, we can get to building. You can help us out by <%= link_to "taking our survey", survey_path, :class =>"faqlink" %>.
<br/>

<br/><h4>What do you mean by “model forms for legal documents”?</h4>
We envision lawyers sharing all kinds of forms --- basically, any document with which a lawyer might want help wording. Just for example, these will include contracts, trusts, demand letters, referral agreements, engagement agreements, issue-specific subpoenas, and practice checklists. Let your imagination go wild.
<br/>

<br/><h4>How will the Vizibid service work?</h4>
Under our current vision (which is subject to change based on your feedback), the Vizibid website will offer four core features to its registered users: (1) a database of searchable forms; (2) the ability to request forms that are not in the database; (3) the ability to upload forms to the database; and (4) the ability to rate and comment on forms.
<br/>

<br/><h4>Can people who are not lawyers use Vizibid?</h4>
No. We want Vizibid’s users to be confident that only lawyers are rating, commenting on, and providing forms. We also don’t want to get into any trouble for assisting non-lawyers with the unauthorized practice of law.
<br/>

<br/><h4>How much will Vizibid cost?</h4>
We are still finding the appropriate pricing structure for the Vizibid service. <%= link_to "Complete our survey", survey_path, :class=>"faqlink"%> and tell us how much you think would be appropriate to pay. 
<br/>

<br/><h4>What can I do right now to get access as soon as the Vizibid service becomes available?</h4>
If you provide us with your name and e-mail address on the <%= link_to "Vizibid home page", root_path, :class=>"faqlink"%>, we will make sure to keep you updated about our progress and to send you a notice once the Vizibid service becomes available.
<br/>

<br/>
<%= link_to "Complete our Survey", survey_path, :id => "surveylink" %>

<br/><br/>

app/views/pages/home.html.erb
<% provide(:title, 'Home')%>

<div class="row">
	<span class="offset3 "><img src="/assets/vizibid-RGB.jpg" style="width: 312px; height: 104px; margin-top: 50px;"/></span><br/><br/>
</div>
<div class = "row">

	<div class = "span7 offset2" style="font-size: 15px; line-height:  22px;">
		Vizibid helps busy lawyers find the exact model legal documents they need. Here's how:
    <br/><br/>
    <ul>
      <li class="splashli"><strong>Search.</strong>&nbsp;Search through Vizibid's ever-growing database of model legal documents for the exact document you need. Download whatever you need.</li>
      <li class="splashli"><strong>Request.</strong>&nbsp;Can't find what you want? Make a request. Other lawyers in the Vizibid community will upload documents in response to your requests.</li>
      <li class="splashli"><strong>Share.</strong>&nbsp;Sometimes other lawyers will request a document you already have. Share your document.</li>
      <li class="splashli"><strong>Review.</strong>&nbsp;Read and write comments about documents. See what other lawyers have to say. Learn the nuances of each document you find.</li>
      <li class="splashli"><strong>Ratings.</strong>&nbsp;Lawyers rate documents they download. Top-rated documents show up at the top of search results. Sort through what you need quickly.</li>
      <li class="splashli"><strong>Lawyers Only.</strong>&nbsp;Every Vizibid document you read was provided by a lawyer. All the comments were written by lawyers. All the ratings were added by lawyers. You can trust what you see.</li>
      <li class="splashli"><strong>Download freely.</strong>&nbsp;Your subscription will include as many downloads as you need. No more paying for documents sight-unseen.</li>
    </ul>
		<br/>
    <div class = "well span5" style="margin-left: 40px;">
  		Vizibid is launching soon. Tell us how to reach you, and we'll let you know when Vizibid launches in your area.
  		<br/><br/>
  		 <%= form_for(@interested_user) do |f| %>
	      	  <%= f.label "Name", :class => "pull-left" %>
            <%= f.text_field :name %><br/>
            <%= f.label "Email", :class => "pull-left" %>
          	<%= f.text_field :email %><br/>
          	<%= f.label "Where do you practice law?", :class => "pull-left" %>
          	<%= f.select :state_licensed, options_for_select(options_for_state_licensed) %><br/>
		  	<%= f.submit "Submit", :class=> "btn btn-info"%>
    	<% end %>
    </div>
	</div>
</div>

app/views/pages/investor.html.erb
<% provide(:title, 'Investor')%>

<div class="offset3"><a href="/"><img src="/assets/vizibid-RGB.jpg" style="width: 312px; height: 104px;"/></a></div>

<% if @approved %>
	<H3 style = "margin-top: 20px;">Click the links below to download our executive summary and investor presentation.</H3><br/>
	<div><%= link_to "Executive Summary", investor_summary_path, :style => "font-size: 15px;"%></div>
	<div style="margin-top: 5px;"><%= link_to "Investor Presentation", investor_deck_path, :style => "font-size: 15px;" %></div>
<% else %>
	<div class="row offset2">
 	<%= form_tag investor_path, :style => "margin-top: 20px; width: 400px;" do %>
 		<H3 style="width: 700px;">Enter the password to access the investor portal.</H3> <br/>
		<%= password_field_tag :password %>
		<%= submit_tag "Submit", :class => "btn btn-info" %>
	<% end %>
</div>
<% end %>

app/views/pages/survey.html.erb
<% provide(:title, 'User Survey')%>

<br/><br/>

<% if rand(0..1) == 0 %>

<iframe src="https://docs.google.com/spreadsheet/embeddedform?formkey=dGhLSFpOblRsZURrN1o4VDJqTGt2Mmc6MQ" width="760" height="2500" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>

<%else%>

<iframe src="https://docs.google.com/spreadsheet/embeddedform?formkey=dFVLa0xrM2k1SFV6aW5vWkc1MV96b1E6MA" width="760" height="2500" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>

<%end%>